[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "falcon_caching"
dist-name = "falcon-caching"
author = "Zoltan Fedor"
author-email = "zoltan.1.fedor@gmail.com"
home-page = "https://github.com/zoltan-fedor/falcon-caching"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Middleware",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]
requires = [
    "falcon >=1.0.0",
    "msgpack"
]
description-file = "README.md"
requires-python = ">=3.7"

[tool.flit.metadata.urls]
Documentation = "https://falcon-caching.readthedocs.io/en/latest/"

[tool.flit.metadata.requires-extra]
test = [
    "aiofiles",
    "coredis>=3.0.0",
    "emcache",
    "flit",
    "pylibmc",
    "pytest >=4.0.0",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-pep8",
    "pytest-xdist",
    "pytest-xprocess",
    "redis",
    "tox",
    "tox-pipenv-install"
]
doc = []
dev = []
all = []